### ISSUE TITLE
Custom ASR

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#105]
https://huggingface.co/clu-ling/whisper-large-v2-japanese-5k-steps
などの任意のmodelをpipeline経由で実行できるようにできますか？
```python
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="clu-ling/whisper-large-v2-japanese-5k-steps")
```
この場合は、`clu-ling/whisper-large-v2-japanese-5k-steps`を指定することで使用できたり...?

**Comment by OzoneAsai** [comment]
たとえばcsvで、
```csv
clu-ling/whisper-large-v2-japanese-5k-steps, pipeline
large-v3, faster_whisper
NadiaHolmlund/Japanese_Fine_Tuned_Whisper_Model, pipeline
espnet/kan-bayashi_csj_asr_train_asr_transformer_raw_char_sp_valid.acc.ave, espnet2
```
などといった具合にできたらいいなぁ...と。

**Comment by litagin02** [comment]
原理的にはできるとは思いますが、あまり選択肢が多くてもユーザーフレンドリーでなく、また他のモデルを調べて使いたい人は自分でコードを書いて書き起こしができるだろうので、あまりこれ以上増やす予定はありません。

**Comment by OzoneAsai** [comment]
あくまで追加できるよという話でしたが...
まあ、増やす予定がないなら
Not plannedでクローズしてください
