### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by RedRayz** [litagin02/Style-Bert-VITS2#119]
READMEの「GitやPython使える人」に記載されているコマンドでは、最新のTorch(現時点で2.2.1)がインストールされます。
しかし、2.2.0以降では`torch.distributed.DistNetworkError: Unknown error`で学習できません。
2.1.2であれば動作したためREADMEにあるtorchをインストールするコマンドでバージョンを明示した方がいいと思います。
`pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118`

**Comment by RedRayz** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1564#issuecomment-1925020157

**Comment by litagin02** [comment]
あーれすみません、2.2.0だとエラーが出ていたのが2.2.1以降では自環境ではそこが修正されてエラーが出ないようになっていたので、そうしていました（>2.2.0を指定したほうがいいというのはあるかもしれないです）。
一応あとで最新版pytorchでもこちらでチェックしてみますが、2.2.1以降でもエラーが出る感じでしょうか？
