### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by kouji1009** [litagin02/Style-Bert-VITS2#144]
![Screenshot 2024-06-18 115649](https://github.com/litagin02/Style-Bert-VITS2/assets/157165730/75a24ec6-00f7-49c1-a35f-5128f9115670)
解決済みの質問に似たようなエラーの対処法があり試してみたんですが、上手くいきません。
一度、rawとesd.listのみにしてからトレーニングを始めても治りません。

使っているesd.listの形式はこのようになっています。
<img width="377" alt="image" src="https://github.com/litagin02/Style-Bert-VITS2/assets/157165730/6d41b844-b701-4ac7-95c0-02e9a5734a81">

**Comment by OzoneAsai** [comment]
事前処理...ボタンを押した後(処理が完了)のesd.listを見せてください。

**Comment by kouji1009** [comment]
<img width="1031" alt="image" src="https://github.com/litagin02/Style-Bert-VITS2/assets/157165730/3d72b9ca-b6ba-4f57-844a-67463f3ffc37">

**Comment by kouji1009** [comment]
<img width="377" alt="image" src="https://github.com/litagin02/Style-Bert-VITS2/assets/157165730/2ba07a9d-a746-4e63-a3cd-c13f39a66254">
公式のこちらのコードを実行した後このようなデータが得られました。

**Comment by OzoneAsai** [comment]
カレントディレクトリが遠くて笑える...笑える？
カレントディレクトリをもっと深いところ、App.batやapp.pyがある場所にしてやってみてください。(これが私のこだわりに他ならない可能性はあるが、colabでも!cd で移動できる...)

**Comment by kouji1009** [comment]
一度新しいnotebookでやり直した後に言われたことをやってみたんですが、変わらずエラーが出ています。

<img width="791" alt="image" src="https://github.com/litagin02/Style-Bert-VITS2/assets/157165730/6da10896-348e-4c16-a9b3-2a19945c65b8">

**Comment by litagin02** [comment]
標準スタイルベクトルの生成のところでエラーになっているようです。
wavs/フォルダの音声ごとに.npyファイルは存在するでしょうか？`recitation001.wav.npy`など。

**Comment by litagin02** [comment]
またこのスタイルベクトルは`preprocess_all`があるセルで自動で生成されるはずなのですが、そこの出力はどのようになっているでしょうか。

**Comment by kouji1009** [comment]
wavsフォルダーには.npyファイルではなく.wav の形式のままになっています。
<img width="269" alt="image" src="https://github.com/litagin02/Style-Bert-VITS2/assets/157165730/c37fb881-9f03-4f55-9016-26842e49db12">

**Comment by litagin02** [comment]
ありがとうございます。wavファイルがあるのはよいのですが、本当はそこに「`recitation001.wav.npy`」等のファイルも出るのですが、それはないですか？

また、`preprocess_all`の結果の出力を教えていただくことはできるでしょうか？

**Comment by litagin02** [comment]
今気づきましたが、見せていただいた画像では`recitation1.wav`ですが書き起こしでは`recietation001.wav`となっていて、そこの不一致でファイルが出てきていない可能性もありますので、書き起こしかファイル名を修正して試していただけないでしょうか。

**Comment by kouji1009** [comment]
ファイル名を修正してみたら学習始まりました。
ありがとうございます！
