### ISSUE TITLE
エラーが出て学習ができない

### ISSUE THREAD

**Issue by hoge46773** [litagin02/Style-Bert-VITS2#156]
エラー内容

Error: 学習に失敗しました:
Traceback (most recent call last):
  File "D:\sbv2\Style-Bert-VITS2\train_ms_jp_extra.py", line 1130, in <module>
    run()
  File "D:\sbv2\Style-Bert-VITS2\train_ms_jp_extra.py", line 132, in run
    dist.init_process_group(
  File "D:\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\distributed\c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "D:\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\distributed\c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "D:\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\distributed\rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "D:\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\distributed\rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

環境　Windows10　使用GPU 1080Ti　使用バージョン2.6.0

学習に入る前までの工程ではエラーは全く出ていません。
最初は自動インストールだとPytorch2.4.0がインストールされなかったのかなと思い、仮想環境にて「pip install torch==2.4.0+cu118 torchvision==0.19.0+cu118 torchaudio==2.4.0+cu118 --index-url https://download.pytorch.org/whl/cu118」などやってみたのですが状況変わらず。
vcpkgでlibuvを手動でインストールしてみても変わらず。
やはりエラー通りインストールされているPytorch2.4.0がlibuvを有効にしてビルドされていないのかと思い、自力でビルドを試みるために
Build Tools for Visual Studio 2022及び必要なコンポーネント（MSVC v143 - VS 2022と、ついでにMSVC v142 - VS 2019）をインストールしてパスも通し、仮想環境にて

pip install cmake

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git checkout v2.4.0
git submodule sync
git submodule update --init --recursive

set USE_LIBUV=1
python setup.py install

とやってみたのですが

Building wheel torch-2.4.0a0+gitd990dad
-- Building version 2.4.0a0+gitd990dad
cmake -GVisual Studio 16 2019 -Ax64 -Thost=x64 -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:\sbv2\Style-Bert-VITS2\pytorch\pytorch\torch -DCMAKE_PREFIX_PATH=D:\sbv2\Style-Bert-VITS2\venv\Lib\site-packages -DPython_EXECUTABLE=D:\sbv2\Style-Bert-VITS2\venv\Scripts\python.exe -DTORCH_BUILD_VERSION=2.4.0a0+gitd990dad -DUSE_NUMPY=True D:\sbv2\Style-Bert-VITS2\pytorch\pytorch
CMake Error at CMakeLists.txt:26 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!

そんなインスタンスないよと返されるばかりで、私の拙い知識では自力では不可能と判断し投稿させて頂きました。
どうすればエラーが出なくなるのかヒントをくださる方がいらっしゃったら有り難いです。

**Comment by kykykkyyz** [comment]
私もhoge46773さんと同じ状況が発生しました、
環境と使用バージョンもhoge46773さんと同じ、自動前処理も問題ありません。
そして"update.bat"を使って、torchを2.3.1+CU118にダウングレードしてみたら、
今度のエラーメッセージ内容は：

07-27 17:46:28 | ERROR  | subprocess.py:33 | Error: train_ms_jp_extra.py --config Data\Voice01\config.json --model Data\Voice01
[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\AI\Style-Bert-VITS2\Style-Bert-VITS2\train_ms_jp_extra.py", line 1130, in <module>
[rank0]:     run()
[rank0]:   File "D:\AI\Style-Bert-VITS2\Style-Bert-VITS2\train_ms_jp_extra.py", line 209, in run
[rank0]:     torch.cuda.set_device(local_rank)
[rank0]:   File "D:\AI\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\cuda\__init__.py", line 399, in set_device
[rank0]:     torch._C._cuda_setDevice(device)
[rank0]: AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'


torch 2.4+CU118の時のエラーは'PyTorch was build without libuv support'
torch 2.3.1+CU118の時のエラーは'torch._C' has no attribute '_cuda_setDevice'

このエラーをどうしたら解消できますかどなたか教えていただけますお願いします。

**Comment by kykykkyyz** [comment]
今日私もStyle-Bert-VITS2を再インストールして、音声モデルを作ることに成功しました。

実は私もkeisasa00さんと同じ音声の文字起こしの問題がありました、エラーメッセージもほとんど同じです。
ですから今日keisasa00さんが音声の文字起こしの問題が解決の報告を見たら、
私もkeisasa00さんを真似して、"sbv2.zip"を再ダウンロードし、Style-Bert-VITS2を再インストールしました。

そしたら、HuggingFaceのWhisperを使う時の音声の文字起こしも同じ'utf-8' codecのエラーが出るですけど、
Whisperを使うのチェックを外したら問題なくesd.listを生成成功しました。
そしてそのまま学習のページで自動前処理→学習をしたら、音声モデルも生成成功しました。

これで私の問題も解決しましたのでここで報告します、私もお騒がせしてしまいすいませんでした。

**Comment by litagin02** [comment]
https://github.com/litagin02/Style-Bert-VITS2/issues/155#issuecomment-2253741303
おそらくまだPyTorch2.4系での何らかの不具合がある模様で、上のところで2.4系を使わないようにとりあえず現在修正しました
これの修正で治ったのかもしれません。

また、HuggingFaceのWhisperを使うば場合に失敗するのは、（まだ原因の特定はできていませんが）ffmpegが入っていないことにもしかしたら由来するかもしれないので、ffmpegを導入してみたらそちらが使えるようになるかもしれません。

**Comment by hoge46773** [comment]
作者様がsbv2.zipの中身を更新して下さったおかげで、更新されたファイルで再インストールを行い、たった今こちらでもエラーなく学習が開始されたのを確認しました。
更新どうもありがとうございました。お手数おかけ致しました。
