### ISSUE TITLE
スタイルが作成できない

### ISSUE THREAD

**Issue by skeleton66** [litagin02/Style-Bert-VITS2#158]
colab版で、以下のようなエラーが発生して
フォルダからスタイルが生成できません。
![スクリーンショット 2024-08-01 095814](https://github.com/user-attachments/assets/425ce3e1-5a38-4a86-b1f2-ade847d67ac1)

**Comment by litagin02** [comment]
報告ありがとうございます。
遅くなりましたが最近のアップデートで修正しました。
