### ISSUE TITLE
UMAPからのDBSCANが分割されにくめ？

### ISSUE THREAD

**Issue by darai0512** [litagin02/Style-Bert-VITS2#16]
## UMAPからのDBSCANが分割されにくめ

デフォ値からかなり値を下げないと分割されない印象。
3時間分くらいのそこそこ感情種類多めのデータで、eps<0.3からようやく（min_samplesはこれに関してはあまり寄与してなさそう。むしろeps小さい状態で増やすとスタイルも増える）

## 一度UIリロードしないと全部ノイズになる？

~UMAP -> t-SNEにしてDBSCANし直すと必ず全部ノイズになる。リロードすると同じパラメータでも結果が変わる。~

これはたまたまそうなった可能性が高そうで、再現性がないことも多いです。

**Comment by litagin02** [comment]
自分もそういう印象をちょっと持ってます。パラメータ値の問題だろうので少しいろいろ調整してみます。

**Comment by litagin02** [comment]
UMAPの場合はDBSCANのepsは0.3くらいから調整が良さげです。
