### ISSUE TITLE
音声の文字起こしを開始するタイミングでフリーズしてしまう

### ISSUE THREAD

**Issue by Haiiroinu** [litagin02/Style-Bert-VITS2#173]
音声のスライスは特に問題なく行えるのですが、文字起こしのタイミングになると0%の状態から全く動かなくなってしまいます。
フリーズしてから1時間は放置していたのですが、変わらずフリーズしたままでした…
プログラミング言語に疎い私では原因を特定できなかったので、お力を貸していただきたいです。

Running app.py...
10-23 23:45:05 | DEBUG  | __init__.py:92 | try starting pyopenjtalk worker server
10-23 23:45:06 | DEBUG  | __init__.py:130 | pyopenjtalk worker server started
10-23 23:45:16 |WARNING | tts_model.py:397 | No model files found in model_assets\.cache, so skip it
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
10-23 23:45:39 |  INFO  | dataset.py:18 | Start slicing...
10-23 23:45:39 |  INFO  | subprocess.py:23 | Running: slice.py --model_name aiko --min_sec 2 --max_sec 12 --min_silence_dur_ms 700 --input_dir inputs
10-23 23:45:42 |  INFO  | slice.py:167 | Found 168 audio files.
100%|████████████████████████████████████████████████████████████████████████████████| 168/168 [00:09<00:00, 18.41it/s]
10-23 23:45:52 |  INFO  | slice.py:265 | Slice done! Total time: 8.01 min, 131 files.
10-23 23:45:53 |SUCCESS | subprocess.py:38 | Success: slice.py --model_name aiko --min_sec 2 --max_sec 12 --min_silence_dur_ms 700 --input_dir inputs
10-23 23:46:12 |  INFO  | subprocess.py:23 | Running: transcribe.py --model_name aiko --model large-v3 --compute_type bfloat16 --language ja --initial_prompt "こんにちは。元気、ですかー？ふふっ、私は……ちゃんと元気だよ！" --num_beams 1 --use_hf_whisper --batch_size 16
10-23 23:46:15 |  INFO  | transcribe.py:203 | Loading HF Whisper model (openai/whisper-large-v3)
  0%|                                                                                                                                | 0/131 [00:00<?, ?it/s]
10-23 23:46:20 |  INFO  | transcribe.py:70 | generate_kwargs: {'language': 'ja', 'do_sample': False, 'num_beams': 1, 'no_repeat_ngram_size': 10}

**Comment by Haiiroinu** [comment]
念のため、その時の文章をコピペしておいたメモ帳も添付させていただきます。
[01.txt](https://github.com/user-attachments/files/17495277/01.txt)

**Comment by Haiiroinu** [comment]
> 音声のスライスは特に問題なく行えるのですが、文字起こしのタイミングになると0%の状態から全く動かなくなってしまいます。 フリーズしてから1時間は放置していたのですが、変わらずフリーズしたままでした… プログラミング言語に疎い私では原因を特定できなかったので、お力を貸していただきたいです。
> 
> 実行中 app.py... 10月23日 23時45分05秒 |デバッグ |**初.py**:92 |PyOpenJTorkワーカーサーバーを起動してみてください 10-23 23:45:06 |デバッグ |**初代** .py:130 |PyOpenJTharkワーカーサーバーが開始しました 10-23 23:45:16 |警告 |tts_model.py:397 |model_assets.cacheにモデルファイルが見つからないため、スキップしてください 情報:指定されたパターンのファイルが見つかりませんでした。
> 
> * ローカル URL で実行: http://127.0.0.1:7860
> 
> 公開リンクを作成するには、. 10月23日 23:45:39 |お知らせ |dataset.py:18 |スライス開始... 10月23日 23:45:39 |お知らせ |subprocess.py:23 |走行中:slice.py - model_name aiko - min_sec 2 - max_sec 12 - min_silence_dur_ms 700 - input_dir入力 10-23 23:45:42 |お知らせ |slice.py:167 |168個のオーディオファイルが見つかりました。 100%|████████████████████████████████████████████████████████████████████████████████|168/168 [00:09<00:00, 18.41it/s] 10-23 23:45:52 |お知らせ |slice.py:265 |スライス完了!合計時間:8.01分、131ファイル。 10月23日 23:45:53 |サクセス |subprocess.py:38 |成功:slice.py - model_name 愛子 - min_sec 2 - max_sec 12 - min_silence_dur_ms 700 - input_dir入力 10-23 23:46:12 |お知らせ |subprocess.py:23 |走行中:transcribe.py - model_name aiko - model large-v3 - compute_type bfloat16 - language ja - initial_prompt "こんにちは。元気、ですかー？ふふっ、私は……num_beams 1 - use_hf_whisper - batch_size 16 10-23 23:46:15 |お知らせ |transcribe.py:203 |HF Whisper モデルの読み込み中 (openai/whisper-large-v3) 0%| |0/131 [00:00<?, ?IT/S] 10-23 23:46:20 |お知らせ |transcribe.py:70 |generate_kwargs: {'language': 'ja', 'do_sample': False, 'num_beams': 1, 'no_repeat_ngram_size': 10}`share=True``launch()`

**Comment by Mofa-Xingche** [comment]
whisper-large-v3モデルのダウンロード・キャッシュの問題:

Whisperのlarge-v3モデルはメモリを大量に使用するので、メモリ不足の可能性:

--compute_type bfloat16を使用しているので、GPUがbfloat16に対応してない場合は問題が発生する可能性が
