### ISSUE TITLE
需要が高いマージ機能[複数の感情スタイルがあるモデル同士をマージ]の要望について

### ISSUE THREAD

**Issue by Mofa-Xingche** [litagin02/Style-Bert-VITS2#181]
@litagin02 すみません失礼します

![無題grgr](https://github.com/user-attachments/assets/51501b95-7c16-42d5-a878-6be06e34d881)
添付した画像のように、3つの感情スタイルが入ったモデル同士を融合して、3つの感情スタイルが入った新たなモデルを作る事はできますか？

モデル一つに感情一つのモデルならマージできる事を知っていますが、感情スタイル名が同じスタイルが複数入ったモデルの場合、融合して↑の図のようにできますか？
この機能は、ゲームや会話アプリなどで使える””自由””なモデルを作るために絶対必要です、
マージ後のモデルに感情スタイルが一つしか付けられないと、日本中のゲームキャラや会話アプリが、声の感情を変えるために毎回モデルのロードで10秒ぐらいかかる事になります

**Comment by Mofa-Xingche** [comment]
すみません失礼します。あーこれ、音声からスタイルベクトル取得して、reference audioのやつでやればスタイルIDなんかいらないのかなぁ

**Comment by litagin02** [comment]
> 添付した画像のように、3つの感情スタイルが入ったモデル同士を融合して、3つの感情スタイルが入った新たなモデルを作る事はできますか？

現状のマージ機能のWebUIにてスタイルもご所望のようにマージする機能がすでに存在しているので、ご確認の上お使いください。
