### ISSUE TITLE
マージ済みモデルはonnx化できますか？

### ISSUE THREAD

**Issue by Mofa-Xingche** [litagin02/Style-Bert-VITS2#182]
①マージ済みモデルはonnx化できますか？
➁複数の感情スタイルが入ったマージ済みモデルはonnx化できますか？

**Comment by litagin02** [comment]
現状はONNXが公式にはまだmasterブランチでサポートしていないので、予定となりますが、解答は以下のとおりです。
1. はい、できます
2. はい、できます
