### ISSUE TITLE
モデルの名前、話者名、スタイル名を後から変更できますか

### ISSUE THREAD

**Issue by Mofa-Xingche** [litagin02/Style-Bert-VITS2#187]
モデルの名前、話者名、スタイル名を後から変更できますか
上の三つの要素の中で、変更できないものはありますか？

**Comment by litagin02** [comment]
ありません。
モデルの名前：単純にファイルやフォルダを変更すればよいです
話者名、スタイル名：config.jsonを書き換えれば変更できます。
