### ISSUE TITLE
is ONLY japanese supported for tone adjustement and emotions adjustement?

### ISSUE THREAD

**Issue by AIpythonAI** [litagin02/Style-Bert-VITS2#27]
I was reading the code and saw this:
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/156720940/4bd31c0f-4560-40c6-8bee-066535530c1d)

So?

**Comment by litagin02** [comment]
"tone" in this setting is a kind of Japanese accent (each mora has low or high, e.g. "アメリカ(A Me Ri Ka" (America in Japanese) has a tone "A: low Me: High, Ri: High, Ka: High". It's specific to Japanese, so this tone adjustment is currently Japanese only (but English uses another "tone" embedding in this model but I haven't checked that).

On the other hand, emotion adjustment (called "Style" in this repo) is not specific to Japanese, so can be used for English and Chinese.
