### ISSUE TITLE
server_fastapi.py を実行した際に発生するエラーについて

### ISSUE THREAD

**Issue by gitpullpull** [litagin02/Style-Bert-VITS2#28]
####  エラー内容
通常のwebUIの起動や推論、学習は正常に行うことが出来ましたが、
server_fastapi.pyを実行した場合、HParams オブジェクトに spk2id 属性がないというエラーが出ます。

#### エラーログ

(venv) D:\free_soft\Style-Bert-VITS2>python server_fastapi.py
01-16 21:44:49 |  INFO  | server_fastapi.py:85 | Loading models...
D:\free_soft\Style-Bert-VITS2\venv\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
01-16 21:44:52 |  INFO  | utils.py:168 | Loaded 'model_assets\jvnv-F1\jvnv-F1.safetensors' (iteration 198)
01-16 21:44:55 |  INFO  | utils.py:168 | Loaded 'model_assets\jvnv-F2\jvnv-F2.safetensors' (iteration 151)
01-16 21:44:57 |  INFO  | utils.py:168 | Loaded 'model_assets\jvnv-M1\jvnv-M1.safetensors' (iteration 239)
01-16 21:45:00 |  INFO  | utils.py:168 | Loaded 'model_assets\jvnv-M2\jvnv-M2.safetensors' (iteration 169)
Traceback (most recent call last):
  File "D:\free_soft\Style-Bert-VITS2\server_fastapi.py", line 86, in <module>
    load_models(model_holder)
  File "D:\free_soft\Style-Bert-VITS2\server_fastapi.py", line 54, in load_models
    model = Model(
  File "D:\free_soft\Style-Bert-VITS2\common\tts_model.py", line 36, in __init__
    self.spk2id: Dict[str, int] = self.hps.data.spk2id
AttributeError: 'HParams' object has no attribute 'spk2id'

#### 実行環境
python 3.10.9
windows 10

torch                     2.1.2+cu118
torch-audiomentations     0.11.0
torch-pitch-shift         1.2.4
torchaudio                2.1.2+cu118
torchmetrics              1.3.0
torchvision               0.16.2+cu118

**Comment by litagin02** [comment]
jvnv-M2の後に読み込まれているモデルフォルダの中のconfig.jsonにspk2idが入っていないようです。通常は学習の際に自動的に作られるはずなのですが、破損等していないでしょうか？

**Comment by gitpullpull** [comment]
破損したモデルが存在するフォルダを削除した結果、正常に動作しました。
ありがとうございます。
