### ISSUE TITLE
I am looking for adding "tone" and "emotion/style" in a technology similar to "rvc-tts-edge" (your other repo)

### ISSUE THREAD

**Issue by APISeeker** [litagin02/Style-Bert-VITS2#29]
Hello, 
Is this the right place to continue using rvc-tts-edge but with tone modificaiton and emotions modificaiton? I would like to be able to use these 2 options in the other repositoruy of rvc tts, don't know if it's possible ?

**Comment by litagin02** [comment]
rvc-tts-webui uses edge-tts as a source audio of TTS, and we cannot control emotions and tones of ouputs of edge-tts, so I think it's difficult.

**Comment by APISeeker** [comment]
So we should look for a way to "take edgetts audio -> modify its tone/emotion(style) -> insert it to rvc-tts-edge"? 

Wonder if it the step 2 is doable or not. (Modifying tone and style of an existing already audio)

**Comment by litagin02** [comment]
I'm not a specialist of such kind of things, so I don't know it's doable or not, and is not related for this repo.

**Comment by APISeeker** [comment]
OK @litagin02, I have a request, I was not able to geenrate CHINESE audio by inserting chinese text to rvc tts (https://github.com/litagin02/rvc-tts-webui) Could you re-open the repository please? I would like to explore the issues and see if someone had the same issue as me: 
```
.....\communicate.py", line 458, in save
    with metadata, open(audio_fname, "wb") as audio:
OSError: [Errno 22] Invalid argument: 
```

Thanks in advance. ^^
