### ISSUE TITLE
Language: JP で音声合成できない

### ISSUE THREAD

**Issue by educator-art** [litagin02/Style-Bert-VITS2#31]
## 試したこと
Style-Bert-VITS2をインストールして音声合成を実行しましたが、ERRORが発生しました。
下記バッチを試しましたが同じ結果でした。なお、ZHやENでは音声合成ができました。

- Install-Style-Bert-VITS2-CPU.bat
- Install-Style-Bert-VITS2.bat

![image](https://github.com/litagin02/Style-Bert-VITS2/assets/153011054/daa66db3-8512-4128-9e5c-4423fe62fd46)

## 聞きたいこと
エラーの原因を探りたいのですが、エラーログなどありましたら
ディレクトリ、ファイル名を教えて頂けませんか？
また、同様の事象を確認しているでしょうか？対応方法などありましたら教えてください。

## 補足事項
GPUは、Geforce GTX 1630(VRAM: 4GB)を使用しています。
[EasyBertVits2](https://github.com/Zuntan03/EasyBertVits2)ではVRAM:8GBが要件となっていますが、
Style-Bert-VITS2ではGPUの要件はありますでしょうか？問題の切り分けが出来ればと思います。

**Comment by litagin02** [comment]
ご不便をおかけして申し訳ありません。
エラーログは開いているターミナル（コマンドプロンプト）に表示されているかと思います。
VRAMについては推論ならばVRAMはそこまで必要ないと思っています。

日本語のみエラーということなので、そこの日本語処理部分のライブラリがなにかエラーを出しているかもしれません。教えていただければ幸いです。
