### ISSUE TITLE
Implementation of a New Language

### ISSUE THREAD

**Issue by SoshyHayami** [litagin02/Style-Bert-VITS2#32]
Hi, I see the approach Bert-VITS2 (which this fork apparently is based on) is taking is a bit different compared to other TTS models, especially other implementations of VITS2's paper. so I'm a bit confused about how to implement a new language except for the three already supported here.

Can you give me a rough summary of the pipeline for this purpose? I assume we need a Bert model, which is readily available( I assume, any Bert model, good at masked language modelling should suffice); and need to pre-train the TTS on roughly 200 hrs of data. but I'm very confused about the pre-processing steps. I usually use Bootphon's Phonemizer (with the espeak backend, I know it doesn't work well with Japanese, but so far it's about the only viable option for my language) but I also see there's a lot of pre-processings done to capture tones, especially for Japanese(which I am familiar with) and Chinese. 

Can you guide me on this? 

Anyway, Thanks in advance.

**Comment by litagin02** [comment]
What I can say about that is that you need custom `g2p` function in the same way as japanese, chinese and english in text folder, which gives phonemes list, tone embeddings, and word2phone list (which word corresponds to which phonemes).
See
https://github.com/fishaudio/Bert-VITS2/discussions/270

**Comment by yiwei0730** [comment]
I would like to ask additional questions. I have prepared new bert and new languages ​​(Korean and vitenames) for training, and loaded the original weight (the original length is loaded, and the excess length is initialized), but I found that the training After they came out, they all made RRRRR sounds.

I would like to ask if you have any ideas on how to retrain the use of a new language.
