### ISSUE TITLE
「ん」の読みについてのバグ

### ISSUE THREAD

**Issue by litagin02** [litagin02/Style-Bert-VITS2#36]
「三円」等が「`s a n e n`」になるため、カタカナでのアクセント調整のところが「サネン」になり、また子音母音判定のところでエラーもたまに出る。

「ん」の音素表記が`N`でなく`n`なことから由来しているバグだが、現在の音素表記で解決できるのか……は謎

**Comment by litagin02** [comment]
内部ではNを使うようにしてver 2.0で解決したはず

**Comment by Aspena2022** [comment]
**ん** を **nn** と表記してみては？
**し** は **sh i** とかってなってますよね。
なら２文字使って nn でもよさそうな気がします。

**三円** -> **s a nn e n**
これならサネンにはならないのでは。

**Comment by litagin02** [comment]
すみませんこれはもう内部で「N」を使うことにして現在は解決しています。
