### ISSUE TITLE
 Bert-VITS2 JP-Extra modelダウンロード

### ISSUE THREAD

**Issue by HIN0209** [litagin02/Style-Bert-VITS2#39]
Bert-VITS2 JP-Extra modelのダウンロードは下のhuggingfaceからするようですが，style_vectors.npyとconfig.jsonは見当たりません．また，D_0. G_0, WD_0.safetensorsを配置すればいいのですか？
https://huggingface.co/litagin/Style-Bert-VITS2-2.0-base-JP-Extra/tree/main
あるいはjvnv-F1などはすでにJP-Extra対応ですか？

よろしくお願いします．

**Comment by litagin02** [comment]
通常のインストール（バッチファイルの実行もしくは`python initialize.py`の実行）のときに、既にこれらの事前学習済みモデルはダウンロードされます。これらのD_0, G_0, WD_0のファイルは学習にのみ用いられるもので、音声合成には使えません（よってstyle_vectors.npyとconfig.jsonは関係ありません）。

jvnv-F1等のモデルは、今のところは旧バージョンのモデルですが、これは音声合成にのみ用いられるものなので、学習には関係ありません。また旧バージョンですが音声合成には使えます。
（そのうちJP-Extra版のモデルに置き換えることを予定しています）。

**Comment by HIN0209** [comment]
解説ありがとうございます。Zennの記事も大変参考になりました。
