### ISSUE TITLE
2つのスタイルを掛け合わせる(merge)ことは実装次第では可能ですか？

### ISSUE THREAD

**Issue by ando-s** [litagin02/Style-Bert-VITS2#45]
2つのスタイルを掛け合わせる(merge)ことは実装次第では可能でしょうか。
例えばSad✖️Angryであるスタイルとなります。もしくはそのようなスタイルを作るといった形になるでしょうか。
技術に乏しく教えていただけると幸いです。🙇

**Comment by litagin02** [comment]
同一モデル上でということでしょうか。
現在のマージツールではスタイルのマージも行うので、マージ元に同じモデルを選択してからマージツールからスタイルマージで新しいスタイルを作ることが可能なはずです。

**Comment by ando-s** [comment]
ご回答いただきありがとうございます。
同一モデル上の想定でした。
今後も何か疑問点が生じた際には、またご指導いただけますと幸いです。
ありがとうございました。
