### ISSUE TITLE
Value error: Unexpected phone: u

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#46]
``
![スクリーンショット 2024-02-09 214908](https://github.com/litagin02/Style-Bert-VITS2/assets/56304837/cec9069e-6403-4e53-8bab-ffc357934042)

外部リンク

神経科学の立場からの解説
02-09 21:42:06 |  INFO  | infer.py:28 | Using normal model
c:\WorkSpace\Style-Bert-VITS2\venv\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")   
02-09 21:42:07 |  INFO  | utils.py:168 | Loaded 'model_assets\tukuyomi\tsukuyomi-chan_e154_s4000.safetensors' (iteration 154)
c:\WorkSpace\Style-Bert-VITS2\venv\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
WARNING: JPCommonLabel_insert_pause() in jpcommon_label.c: First mora should not be short pause.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be long vowel symbol.
02-09 21:42:28 | DEBUG  | japanese.py:529 | phones: ['u', 'g', 'o', 'w', 'a', ',', 'h', 'i', 'N', 'd', 'u', 's', 'u', 't', 'a', 'a', 'n', 'i', 'i', 'g', 'o', 't', 'o', 'sh', 'i', 't', 'e', 'd', 'o', 'o', 'i', 'ts', 'u', 'g', 'e', 'N', 'g', 'o', 'm', 'a', 't', 'a', 'w', 'a', 'h', 'o', 'o', 'g', 'e', 'N', 'r', 'e', 'N', 'z', 'o', 'k', 'u', 't', 'a', 'i', 't', 'o', 'sh', 'i', 't', 'e', 'a', 'ts', 'u', 'k', 'a', 'w', 'a', 'r', 'e', 'r', 'u', 'k', 'o', 't', 'o', 'g', 'a', 'a', 'r', 'u']
02-09 21:42:28 | DEBUG  | japanese.py:530 | phone_tone_list: [('g', 1), ('o', 1), ('w', 0), ('a', 0), ('h', 0), ('i', 0), ('N', 1), ('d', 1), ('u', 1), ('s', 1), ('u', 1), ('t', 1), ('a', 1), ('a', 1), ('n', 1), ('i', 1), ('i', 1), ('g', 
0), ('o', 0), ('t', 0), ('o', 0), ('sh', 0), ('i', 0), ('t', 1), ('e', 1), ('d', 0), ('o', 0), ('o', 1), ('i', 1), ('ts', 1), ('u', 1), ('g', 1), ('e', 1), ('N', 0), ('g', 0), ('o', 0), ('m', 0), ('a', 0), ('t', 1), ('a', 1), ('w', 0), ('a', 0), ('h', 0), ('o', 0), ('o', 1), ('g', 1), ('e', 1), ('N', 1), ('r', 1), ('e', 1), ('N', 1), ('z', 1), ('o', 1), ('k', 1), ('u', 1), ('t', 1), ('a', 1), ('i', 0), ('t', 0), ('o', 0), ('sh', 0), ('i', 0), ('t', 1), ('e', 1), ('a', 0), ('ts', 1), ('u', 1), ('k', 1), ('a', 1), ('w', 1), ('a', 1), ('r', 1), ('e', 1), ('r', 1), ('u', 1), ('k', 0), ('o', 0), ('t', 1), ('o', 1), ('g', 0), ('a', 0), ('a', 1), ('r', 0), ('u', 0)]
02-09 21:42:28 | DEBUG  | japanese.py:531 | result: []
02-09 21:42:28 | DEBUG  | japanese.py:532 | tone_index: 0
02-09 21:42:28 | DEBUG  | japanese.py:533 | phone: u
02-09 21:42:28 | ERROR  | app.py:115 | Value error: Unexpected phone: u
02-09 21:43:21 |  INFO  | tts_model.py:101 | Start generating audio data from text:
ドンドン説
音響から自然物に関する語が出来たもの

ピカッ！ゴロゴロからかみなりライ、ザーッからみずスイなど

エイヤコーラ説
かけ声から行動に関する語が出来たもの

停止を促す声からとまるテイ、働く時の声からはたらくロウなど

この説は、集団行動をとる時の意味の無いはやし歌が、世界各地に残っている事からも裏付けられる

なお、言語が生まれたのが地球上の一ヶ所なのか、複数ヶ所なのかも分かっていない

生物学的な観点から言語の起源を探ろうという試みもある
最近の分子生物学的研究によれば、2と名づけられている遺伝子に生じたある種の変異が言語能力の獲得につながった可能性がある  
さらにその変異は現生人類とネアンデルタール人が分化する以前の3040万年前にはすでに生じていたとの解析結果が発表されており 
、現生人類が登場とともに既に言語を身につけていた可能性も考えられる
しかし2は言語能力を有しない他の動物の多くが持っていること、2の変異が言語能力の獲得の必要条件であるとの直接的な証明はま 
だなされていないことなどに留意する必要がある

変化

生物の場合には、進化が止まった生物が現在も生き残っている生きている化石と呼ばれるものがある
また、一見似ている2種類が全然別の種類から進化していたというケースもある
言語にも同じような現象が起きており、その変化の速度は一定ではなく、侵略交易移動等他民族との接触が多ければ、その時言語も 
大きく変化する
代表例として英語、フランス語、ルーマニア語、アルバニア語、アルメニア語等がある
逆に接触が少ないとほとんど変化しなくなる
代表例としてドイツ語、アイスランド語、ギリシャ語、スラヴ語派、バルト語派、サンスクリット語等があり、特にアイスランド語 
は基本文法が1000年前とほとんど変っていない

言語はもともといくつかの祖語から分化したと考えられており、同一の祖語から発生したグループを語族と呼ぶ
語族はさらに語派、語群、そして言語と細分化されていく
世界の大多数の言語はなんらかの語族に属するが、なかには現存する他の言語と系統関係が立証されておらず、語族に分類できない 
孤立した言語も存在する
また、地理文化的に近接する異なった系統の言語が相互に影響しあい顕著に類似する事例も見られ、これは言語連合と呼ばれる     

同一語族に属する言語群の場合、共通語彙から言語の分化した年代を割り出す方法も考案されている

一つの言語の言語史を作る場合、単語綴り発音文法等から古代中世近代と3分割し、例えば中世フランス語等と呼ぶ

ある言語と他の言語が接触した場合、両言語の話者の交流が深まるにつれて様々な変化が発生する
これを言語接触という
言語接触によって、両言語には相手の言語から語彙を借用した借用語が発生するほか、交流が深まるにつれて商業や生活上の必要か 
ら混成言語が発生することがある
この混成言語は、初期にはピジン言語と呼ばれる非常に簡略化された形をとるが、やがて語彙が増え言語として成長してくると、『 
クレオール言語という新しい言語となった』と見なす
クレオール言語はピジン言語と比べ語彙も多く、何よりきちんと体系だった文法が存在しており、一個の独立した言語と見なして全 
く差し支えない
クレオール言語はピジン言語と違い、母語話者が存在する、つまり幼いころから主にその言語を話して育った人々がいる、というこ 
とも特徴である

中世の世界においてはしばしば、文語と日常使用する言語との間には隔たりがみられ、なかには中世ヨーロッパにおけるラテン語の 
ようにその土地の言葉と全く異なる言語を文章語として採用している世界も存在した
ラテン語は欧州において知識人の間の共通語として用いられ、ルネサンスなどで大きな役割を果たしたが、やがて印刷術の発展や宗 
教改革などによって各国において使用される日常言語が文語として用いられるようになった
この際、それまで方言の連続体しか持たなかった各国において、その言語を筆記する標準的な表記法が定まっていき、各国において 
国内共通語としての標準語が制定されるようになった
これは出版物などによって徐々に定まっていくものもあれば、中央に公的な言語統制機関を置いて国家主導で標準語を制定するもの 
もあったが、いずれにせよこうした言語の整備と国内共通語の成立は、国民国家を成立させるうえでの重要なピースとなっていった 
一方で、標準語の制定は方言連続体のその他の言語を方言とすることになり、言語内での序列をつけることにつながった

最も新しい言語であり、また誕生する瞬間がとらえられた言語としては、ニカラグアの子供達の間で1970年代後半に発生したニカラ 
グア手話がある
これは、言語能力は人間に生得のものであるという考えを裏付けるものとなった

世界の言語

現在世界に存在する言語の数は千数百とも数千とも言われる
1939年にアメリカのルイスハーバートグレイは著書において2796言語と唱え、1979年にドイツのマイヤーが4200から5600言語と唱え 
ており、三省堂の言語学大辞典世界言語編では8000超の言語を扱っている

しかし、正確に数えることはほぼ不可能である
これは、未発見の言語や、消滅しつつある言語があるためだけではなく、原理的な困難があるためでもある
似ているが同じではない言語が隣り合って存在しているとき、それは一つの言語なのか別の言語なのか区別することは難しい       
これはある人間集団を言語の話者とするか方言の話者とするかの問題でもある
たとえば、旧ユーゴスラビアに属していたセルビア、クロアチア、ボスニアヘルツェゴビナ、モンテネグロの4地域の言語は非常に似
通ったものであり、学術的には方言連続体であるセルビアクロアチア語として扱われる
また旧ユーゴスラビアの政治上においても国家統一の観点上、これらの言語は同一言語として扱われていた
しかし1991年からのユーゴスラビア紛争によってユーゴスラビアが崩壊すると、独立した各国は各地方の方言をそれぞれ独立言語と 
して扱うようになり、セルビア語、クロアチア語、ボスニア語の三言語に政治的に分けられるようになった
さらに2006年にモンテネグロがセルビアモンテネグロから独立すると、モンテネグロ語がセルビア語からさらに分けられるようにな 
った
こうした、明確な標準語を持たず複数の言語中心を持つ言語のことを複数中心地言語と呼び、英語などもこれに含まれる

逆に、中国においては北京語やそれを元に成立した普通話と、上海語や広東語といった遠隔地の言語とは差異が大きく会話が成立し 
ないほどであるが、書き言葉は共通であり、またあくまでも中国語群には属していて対応関係が明確であるため、これら言語はすべ 
て中国語内の方言として扱われている

同じ言語かどうかを判定する基準として、相互理解性を提唱する考えがある
話者が相手の言うことを理解できる場合には、同一言語、理解できない場合には別言語とする
相互理解性は言語間の距離を伝える重要な情報であるが、これによって一つの言語の範囲を確定しようとすると、技術的難しさにと 
どまらない困難に直面する
一つは、の言うことをが聞き取れても、の言うことをが聞き取れないような言語差があることである
もう一つは、同系列の言語が地理的な広がりの中で徐々に変化している場合に、どこで、いくつに分割すべきなのか、あるいはまっ 
たく分割すべきでないのかを決められないことである

こうした困難に際しても、単一の基準を決めて分類していくことは、理屈の上では可能である
しかしあえて単一基準を押し通す言語学者は現実にはいない
ある集団を言語話者とするか方言話者とするかには、政治的文化的アイデンティティの問題が深く関係している
どのような基準を設けようと、ある地域で多くの賛成を得られる分類基準は、別の地域で強い反発を受けることになる
そうした反発は誤りだと言うための論拠を言語学はもっていないので、結局は慣習に従って、地域ごとに異なる基準を用いて分類す 
ることになる

言語と方言の区別について、現在なされる説明は二つである
第一は、言語と方言の区別にはなんら言語学的意味はないとする
第二のものはまず、どの方言もそれぞれ言語だとする
その上で、ある標準語に対して非標準語の関係にある同系言語を、方言とする
標準語の選定は政治によるから、これもまた言語と方言の区別に言語学的意味はないとする点で、第一と同じである
この定義では、言語を秤にかけて判定しているのではなく、人々がその言語をどう思っているかを秤にかけているのである

ある言語同士が独立の言語同士なのか、同じ言語の方言同士なのかの判定は非常に恣意的であるが、その一方で、明確に系統関係が 
異なる言語同士は、たとえ共通の集団で話されていても、方言同士とはみなされないという事実も有る
たとえば、中国甘粛省に住む少数民族ユーグ族は西部に住むものはテュルク系の言語を母語とし、東部に住むものはモンゴル系の言 
語を母語としている
両者は同じ民族だという意識があるが、その言語は方言同士ではなく、西部ユーグ語、東部ユーグ語と別々の言語として扱われる   
また海南島にすむ臨高人も民族籍上は漢民族であるが、その言語は漢語の方言としては扱われず、系統どおりタイカダイ語族の臨高 
語として扱われる

使用する文字は同言語かどうかの判断基準としてはあまり用いられない
言語は基本的にどの文字でも表記可能なものであり、ある言語が使用する文字を変更することや二種以上の文字を併用することは珍 
しいことではなく、また文法などに文字はさほど影響を与えないためである
デーヴァナーガリー文字を用いるインドの公用語であるヒンディー語とウルドゥー文字を用いるパキスタンの公用語であるウルドゥ 
ー語は、ヒンドゥスターニー語として同一言語または方言連続体として扱われることがある

話者数の統計順位

母語話者統計で見た話者数

下表の母語話者数および分類は、『エスノローグ第21版』に準拠する
同資料は2021年時点の推計で、中国語は13方言、アラビア語は20方言、ラフンダー語は4方言の合計である

母語話者数と総話者数の差
上図の通り、最も母語話者の多い言語は中国語であるが、公用語としている国家は中華人民共和国と中華民国、それにシンガポール 
の3つの国家にすぎず、世界において広く使用されている言語というわけではない
また、共通語である普通話を含め13個の方言が存在する

上記の資料で話者数2位の言語はスペイン語である
これはヨーロッパ大陸のスペインを発祥とする言語であるが、17世紀のスペインによる新大陸の植民地化を経て、南アメリカおよび 
北アメリカ南部における広大な言語圏を獲得した
2021年度においてスペイン語を公用語とする国々は21カ国にのぼる
さらにほぼ同系統の言語である5位のポルトガル語圏を合わせた新大陸の領域はラテンアメリカと呼ばれ、広大な共通言語圏を形成し
ている

上記の資料で英語の話者人口は4位だが、公用語としては55か国と最も多くの国で話されている
さらに、英語はアメリカ合衆国やイギリスの公用語であるため世界で広く重要視されている
世界の一体化に伴い研究やビジネスなども英語で行われる場面が増え、非英語圏どうしの住民の交渉においても共通語として英語を 
使用する場合があるなど、英語の世界共通語としての影響力は増大していく傾向にある

英語に次ぐ国際語としては、17世紀から19世紀まで西洋で最も有力な国際語であったフランス語が挙げられる
フランス語の話者は2億3000万人とトップ5にも入らないが、フランス語を公用語とする国々はアフリカの旧フランス植民地を中心に29カ国にのぼる

話者数7位のアラビア語も広い共通言語圏を持つ言語である
アラビア語はクルアーンの言語としてイスラム圏全域に使用者がおり、とくに北アフリカから中東にかけて母語話者が多いが、公用 
語とする国々は23カ国にのぼっていて、ひとつのアラブ文化圏を形成している
ただしこれも文語であるフスハーと口語であるアーンミーヤに分かれており、アーンミーヤはさらに多数の方言にわかれている     

国連の公用語は、英語、フランス語、ロシア語、中国語、スペイン語、アラビア語の6つであるが、これは安全保障理事会の常任理事
国の言語に、広大な共通言語圏を持つスペイン語とアラビア語を加えたものである

言語と国家
言語は国家を成立させるうえでの重要な要素であり、カナダにおける英語とフランス語や、ベルギーにおけるオランダ語とフランス 
語のように、異なる言語間の対立がしばしば言語戦争と呼ばれるほどに激化して独立問題に発展し、国家に大きな影響を及ぼすこと 
も珍しくない
東パキスタンのように、西パキスタンの言語であるウルドゥー語の公用語化に反発してベンガル語を同格の国語とすることを求めた 
ことから独立運動が起き、最終的にバングラデシュとして独立したような例もある

こうした場合、言語圏別に大きな自治権を与えたり、国家の公用語を複数制定したりすることなどによって少数派言語話者の不満を 
なだめる政策はよく用いられる
言語圏に強い自治権を与える典型例はベルギーで、同国では1970年に言語共同体が設立され、数度の変更を経てフラマン語共同体、 
フランス語共同体、ドイツ語共同体の3つの言語共同体の併存する連邦国家となった
公用語を複数制定する例ではスイスが典型的であり、それまでドイツ語のみであった公用語が1848年の憲法によってドイツ語フラン 
ス語イタリア語の三公用語制となり、さらに1938年にはロマンシュ語が国語とされた
この傾向が特に強いのはインドであり、1956年以降それまでの地理的な区分から同系統の言語を用いる地域へと州を再編する、いわ 
ゆる言語州政策を取っている

公用語、共通語、民族語

国家における言語の構造は、公用語共通語民族語の三層の構造からなっている
もっとも、公用語と共通語、また三層すべてが同じ言語である場合はその分だけ層の数は減少する

日本を例にとれば、各地方ではその地方の方言を使っている
つまり、同じ地方のコミュニティ内で通用する言語を使用している
これが他地方から来た人を相手にする場合となると、いわゆる標準語を使用することとなる
日本では他に有力な言語集団が存在しないため、政府関係の文書にも日本標準語がそのまま使用される
つまり、共通語と公用語が同一であるため、公用語方言の二層構造となっている

公用語と共通語は分離していない国家も多いが、アフリカ大陸の諸国家においてはこの三層構造が明確にあらわれている
これらの国においては、政府関係の公用語は旧宗主国の言語が使用されている
学校教育もこの言語で行われるが、民族語とかけ離れた存在であることもあり国民の中で使用できる層はさほど多くない
この穴を埋めるために、各地域においては共通語が話されている
首都がある地域の共通語が強大化し、国の大部分を覆うようになることも珍しくない
しかし文法の整備などの遅れや、国内他言語話者の反対、公用語の使用能力がエリート層の権力の源泉となっているなどの事情によ 
って、共通語が公用語化はされないことがほとんどである
その下に各民族の民族語が存在する

言語の生物学
詳細は心理言語学及び、神経言語学を参照

言語機能は基本的にヒトに固有のものであるため、言語の研究には少数の例外を除き動物モデルを作りにくい
そのため、脳梗塞などで脳の局所が破壊された症例での研究や、被験者に2つの単語を呈示しその干渉効果を研究するなどの心理学的
研究が主になされてきたが、1980年代後半より脳機能イメージング研究が手法に加わり、被験者がさまざまな言語課題を行っている 
ときの脳活動を視覚化できるようになった

言語に関する脳の領域
古典的なブローカ領域、ウェルニッケ領域のほか、シルヴィウス裂を囲む広い範囲にわたっている
脳梗塞などで各部が損傷されると、それぞれ違ったタイプの失語が出現する
例えば左前頭前野付近の損傷で生じるブローカ失語は運動失語であり、自発語は非流暢性となり復唱、書字も障害される
左側頭葉付近の障害で生じるウェルニッケ失語は感覚失語であり自発語は流暢であるが、言語理解や復唱が障害され、文字による言 
語理解も不良である

ほとんどの右利きの人では、単語、文法、語彙などの主要な言語機能は左半球優位である
しかし声の抑揚の把握、比喩の理解については右半球優位であると言われている

文字の認識には左紡錘状回、中下後頭回が関与するが、漢字とひらがなで活動する部位が異なると言われている

ヒトの発達における言語機能の獲得
これも多方面から研究されている
個人の言語能力は、読字障害、ウィリアムズ症候群、自閉症などのように全体的な知的能力とは乖離することがあり、個体発生やヒ 
トの進化における言語の起源などにヒントを与えている
また、ヒトは環境の中で聴取する音声から自力で文法などの規則を見出し学習する機能を生得的に備えているため、特に教わらなく 
ても言語を学習できるとする生得論という考えも存在する

最近の近赤外線分光法を用いた研究において、生後2から5日の新生児が逆再生よりも順再生の声を聞いたほうが、あるいは外国語よ 
り母国語を聞いたときの方が聴覚皮質の血流増加が大きかったと報告されており、出産前から母体内で言語を聴いていることが示唆 
される

脚注

注釈

出典

関連項目
言語を含む記事名の一覧
言葉
言語学
理論言語学社会言語学社会言語学音声学
歴史言語学歴史言語学
応用言語学
個別言語学
言語力
言葉遊び
言語聴覚療法

外部リンク

神経科学の立場からの解説
WARNING: JPCommonLabel_insert_pause() in jpcommon_label.c: First mora should not be short pause.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be long vowel symbol.
02-09 21:43:44 | DEBUG  | japanese.py:529 | phones: ['u', 'g', 'o', 'w', 'a', ',', 'h', 'i', 'N', 'd', 'u', 's', 'u', 't', 'a', 'a', 'n', 'i', 'i', 'g', 'o', 't', 'o', 'sh', 'i', 't', 'e', 'd', 'o', 'o', 'i', 'ts', 'u', 'g', 'e', 'N', 'g', 'o', 'm', 'a', 't', 'a', 'w', 'a', 'h', 'o', 'o', 'g', 'e', 'N', 'r', 'e', 'N', 'z', 'o', 'k', 'u', 't', 'a', 'i', 't', 'o', 'sh', 'i', 't', 'e', 'a', 'ts', 'u', 'k', 'a', 'w', 'a', 'r', 'e', 'r', 'u', 'k', 'o', 't', 'o', 'g', 'a', 'a', 'r', 'u']
02-09 21:43:44 | DEBUG  | japanese.py:530 | phone_tone_list: [('g', 1), ('o', 1), ('w', 0), ('a', 0), ('h', 0), ('i', 0), ('N', 1), ('d', 1), ('u', 1), ('s', 1), ('u', 1), ('t', 1), ('a', 1), ('a', 1), ('n', 1), ('i', 1), ('i', 1), ('g', 
0), ('o', 0), ('t', 0), ('o', 0), ('sh', 0), ('i', 0), ('t', 1), ('e', 1), ('d', 0), ('o', 0), ('o', 1), ('i', 1), ('ts', 1), ('u', 1), ('g', 1), ('e', 1), ('N', 0), ('g', 0), ('o', 0), ('m', 0), ('a', 0), ('t', 1), ('a', 1), ('w', 0), ('a', 0), ('h', 0), ('o', 0), ('o', 1), ('g', 1), ('e', 1), ('N', 1), ('r', 1), ('e', 1), ('N', 1), ('z', 1), ('o', 1), ('k', 1), ('u', 1), ('t', 1), ('a', 1), ('i', 0), ('t', 0), ('o', 0), ('sh', 0), ('i', 0), ('t', 1), ('e', 1), ('a', 0), ('ts', 1), ('u', 1), ('k', 1), ('a', 1), ('w', 1), ('a', 1), ('r', 1), ('e', 1), ('r', 1), ('u', 1), ('k', 0), ('o', 0), ('t', 1), ('o', 1), ('g', 0), ('a', 0), ('a', 1), ('r', 0), ('u', 0)]
02-09 21:43:44 | DEBUG  | japanese.py:531 | result: []
02-09 21:43:44 | DEBUG  | japanese.py:532 | tone_index: 0
02-09 21:43:44 | DEBUG  | japanese.py:533 | phone: u
02-09 21:43:44 | ERROR  | app.py:115 | Value error: Unexpected phone: u
```

**Comment by litagin02** [comment]
Please update to recent version. The problem here is the parsing of `ー語は、ヒンドゥスターニー語として同一言語または方言連続体として扱われることがある`, and the treatment of the beginning `ー` (long phone symbol). This bug is fixed in version.
BTW this phrase is not intended I think and resulting from inappropriate line break.
