### ISSUE TITLE
々を読んでくれ...

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#47]
ERROR  | app.py:119 | Value error: Cannot read: 々 in:
戦時中,敵が'桂を討ち取った!'と声高々に喚くのを何度も聞いたことがある.桂に限らず,四天王のメンツは大体白羽の矢が立っていたが.

**Comment by OzoneAsai** [comment]
def predict_text(text):
    output = client.predict(
        "Tukuyomi",  # モデル
        "model_assets\Tukuyomi\Tsukuyomi-chan_e154_s4000.safetensors",  # モデルファイル
        text+"A",  # テキスト
        "JP",  # 言語
        None,  # ファイルパス
        0.4,     # SDP比率
        0.6,   # ノイズ
        0.8,   # ノイズ_W
        1.1,   # 長さ
        True,  # 改行で分けて生成
        0.5,     # 改行ごとに挟む無音の長さ（秒）
        None,  # アシストテキスト
        0,     # アシストテキストの強さ
        False,  # アシストテキストを使う
        "Neutral",  # スタイル
        5,     # スタイルの強さ
        text,  # アクセント調整
        False,  # アクセント調整を使う
        "tsukuyomi-chan",  # 話者
        api_name="/tts_fn"
    )
    return output[1]

**Comment by litagin02** [comment]
OpenJTalkから読みを取得しており、それを利用しているだけなので、現在のところはOpenJTalkが読めないとこちらでは対処できません。ユーザー辞書等の実装もありえますが現状は難しいです。

**Comment by OzoneAsai** [comment]
それは...残念ですね。事前処理としてほかの方法で置き換えとかするかなぁ...

02-10 12:33:11 |  INFO  | tts_model.py:101 | Start generating audio data from text:
皆さんのかけがえのない労働を、その成果を、乳飲み子を抱えた母親たちに恐怖させるほどにまで侮辱し、貶（おとし）めた、その真の加害者は誰なのか？
A
02-10 12:33:11 | ERROR  | app.py:119 | Value error: Cannot read: 貶 in:
皆さんのかけがえのない労働を,その成果を,乳飲み子を抱えた母親たちに恐怖させるほどにまで侮辱し,貶'おとし'めた,その真の加害者は誰なのか?

**Comment by OzoneAsai** [comment]
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/56304837/895c8e94-9877-4f9b-8fcc-8f9c34e8ae76)
