### ISSUE TITLE
読みとかの返還

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#48]
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/56304837/da05ea9b-b5e8-4083-a557-f264349237b6)
OpenJTalkのエラーをexceptしてMecabで読みに変換していい感じに...?
https://github.com/neologd/mecab-ipadic-neologd/blob/master/README.ja.md

**Comment by litagin02** [comment]
アクセントも取得する必要があるので、Mecabの外部辞書を使って直接読みを取得する方法がうまくいくかはすぐに方法が分かりません。また単純なpythonライブラリとしても使えないようなので、インストールが複雑になりそうな気がしています。
現状ありうるのはpyopenjtalkのユーザー辞書機能を用いるものだと思いますが、pyopenjtalkのビルド版では対応していないのもあり、すぐには良い方法がありません。

**Comment by OzoneAsai** [comment]
エラー発生箇所だけひらがなにしてもう一度openjtalkに渡す、というのは？

**Comment by litagin02** [comment]
どのように平仮名へ変換しますか？またエラー箇所と言っても`声高々に喚く`等は`々`でエラーがでますが単体では読みが存在しません。エラー箇所が出たところ全てを平仮名にするのはBERT部分やアクセントへの悪影響が大きくあまり現実的ではないと思われます。

**Comment by OzoneAsai** [comment]
https://mitsuba-studio.com/vt_v3/DemoKeyPhrases/demo_mecab
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/56304837/b355e9b8-8c18-4857-a164-e5d4cf01d6b3)
このサイトでは上記のような回答が得られました。
文章をいちどmecab に渡してカラーオープン中トークのエラー発生文字を検索にかけて、それが含まれるトークンをその読み方で置き換えたらいい...かなと思います

**Comment by OzoneAsai** [comment]
でも、声高々は...切り方が
声高/々
になってしまったので、その前の文字を参照する形で...?

**Comment by OzoneAsai** [comment]
ChatGPTによるまとめ

以下のポイントをまとめます：

1. OpenJTalkのエラーをexceptして、Mecabで読みに変換する方法を検討している。
2. アクセント情報も取得する必要があるため、Mecabの外部辞書を利用して直接読みを取得する方法が考えられるが、複雑なインストール手順が必要であると感じている。
3. 現状、pyopenjtalkのユーザー辞書機能を利用することが可能だが、ビルド版では対応していないため、適切な方法が見つかっていない。
4. ![image](https://github.com/litagin02/Style-Bert-VITS2/assets/56304837/d0c101a5-e0d6-43c3-b196-1dc334affba6)提供された例の中では、［hyouki］、［hinshi］、［katsuyoukei］などのトークンが含まれており、これらをMecabで解析して、エラーが発生したトークンをその読み方で置き換える方法を検討している。

**Comment by litagin02** [comment]
基本的にはpyopenjtalkはデフォルトの（辞書追加のない）mecabが使われているため、くださったような品詞分解・読み取得は内部で行われています（`pyopenjtalk.run_frontend()`で同様のmecabからの返答が帰ってきます）。
なのでmecabを使うとしても、要するに新しい辞書を追加する以外の解決法は今のところ無い気がしています。

**Comment by OzoneAsai** [comment]
んー...openJtalkに渡す前にmecabで独立した々を検出して、2文字前が漢字であれば、1文字前と2文字前の間に区切り記号を挿入....?
という処理。
が欲しいと思ったがそれは関係なくて...
そういえば、アクセント調整ってOpenJTalkが関与してくるんですか？

**Comment by litagin02** [comment]
https://www.negi.moe/negitalk/openjtalk.html
OpenJTalkはmecabの読みや形態素情報に加えてアクセントを加えた独自の解析結果が使えるので、アクセント高低はそこから取得されています。

**Comment by OzoneAsai** [comment]
不可能を感じたので最後に要求だけ書き留めようと思います。というか、初期の主張は...無かったことにしましょう。
1、"々"を読めない、というエラーならばその1文字前と2文字前の間に区切りを入れるようにexceptできるなら...

**Comment by litagin02** [comment]
提案ありがとうございます。「々」が読めないときの処理はそれでよさそうではありますが、すぐに実装できるかは分からないのと、これで解決できるかのチェック等や、他に影響が出る可能性もありそうなので、少し考えてみたいと思います。

**Comment by litagin02** [comment]
https://github.com/litagin02/Style-Bert-VITS2/issues/60
読み等の問題はこのIssueへ統合します。
