### ISSUE TITLE
英語と中国語の発音悪くね？

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#50]
中国語は韓国語のように...そう聞こえてしまったことがある。
英語もまたなんか、複雑な単語(例:individualなど)だと発音がやばい

**Comment by litagin02** [comment]
発音については、現在は共通の音素を無理やり使っているので発音が悪い（もしくは共通しない音素ではかなり不自然になる）のはどうしようもありません。
イントネーション・抑揚等についてはfreeze_bertやfreeze_en_bertオプションをtrueにすると増しになるかもしれません。

**Comment by OzoneAsai** [comment]
めっちゃmultilingual なTTS
 https://github.com/coqui-ai/TTS

ユーザー辞書関連

https://github.com/VOICEVOX/voicevox_engine/pull/301

https://github.com/VOICEVOX/voicevox_engine/pull/234

さぁっと、目を通してみてください。ちなみに、TTSはようわからんかった...(TTSというLinuxしか対応しないライブラリーを使ってるからね)

**Comment by litagin02** [comment]
情報ありがとうございます、がTTSの構造についてはBert-VITS2のものを使っているのでこれ以上外国語の性能を上げる方法は分かりません。
ユーザー辞書はVOICEVOXのものはpyopenjtalkのユーザー辞書機能を使っていると認識しているので、それを方法を検討することにします。

**Comment by OzoneAsai** [comment]
[生成した日本語音声](https://drive.google.com/file/d/1Yzy27joANvNVY4UbnduJWmfTYSwO1WHH/view?usp=drivesdk)

Assist textで読点を使いすぎたのでめっちゃ区切れてますw。
ほんっとうに暇な人は聞いてください。27分あります。
また、モデルはつくよみちゃんです。

**Comment by OzoneAsai** [comment]
https://www.dropbox.com/scl/fi/zbqh3tzr354xhqrspn7wx/connected.wav?rlkey=qp18jhypvc4amic6qprjjrphv&dl=0
2Hours, Tsukiyomi-chan

**Comment by litagin02** [comment]
英語と中国語の発音改善に関係する話ではありませんのでご遠慮ください。クローズします。

**Comment by OzoneAsai** [comment]
https://github.com/TencentGameMate/chinese_speech_pretrain
