### ISSUE TITLE
`server_fastapi.py`でのアクセント指定

### ISSUE THREAD

**Issue by litagin02** [litagin02/Style-Bert-VITS2#55]
WebUI上ではアクセント指定ができるが、まだAPI上には実装されていない。どういう形で実装するのが良いかはよくわからない（正解アクセントをリターンするエンドポイントも作る？）

**Comment by WariHima** [comment]
webuiのアクセント指定機能にapi用アクセント位置出力機能を組み込む方法がよいと思う。
api用アクセント位置の形式はこんな感じのイメージ

例
そんなもんしらんけど　(アクセント位置)そんな↑もんしら↑んけど
変換後
3u4n7u8n

数字=文字の位置 u = up n = neutral

**Comment by litagin02** [comment]
`server_editor.py`においてアクセント含むAPIを用意したのでクローズします。
（2つのAPIサーバーを統合するのかとかそういう問題はありますが……）
