### ISSUE TITLE
model_idとspeaker_idについてお聞きしたいですが

### ISSUE THREAD

**Issue by shikichrome** [litagin02/Style-Bert-VITS2#58]
config.jsonにある
"spk2id": {
      "name": 0←ここの数字をいじればいいですか？

APIで一番上のモデルしか正常に再生できなくて....

**Comment by OzoneAsai** [comment]
あぁ、あのURlのModel_idの数字をいじりましょう

**Comment by shikichrome** [comment]
モデルID。GET /models/infoのkeyの値を指定ください
のkeyの場所がちょっとわからなくて....
教えていただけますか？

**Comment by OzoneAsai** [comment]
URLのportの数字まで消して、

/models/info

と、ペーストしてブラウザでひらけばreturnにIDが書いてあると思いますよ。
最悪、ローラーしたら問題ないんですけどねw

**Comment by OzoneAsai** [comment]
model infoって、引数無かったと思うんですけどね。(措定するものはないということ)

**Comment by shikichrome** [comment]
すみません、speaker_nameはmodel_nameですか？

**Comment by OzoneAsai** [comment]
例えば、これをご覧ください。
model_idろspeaker_nameが共存していますね
```

http://127.0.0.1:5000/voice?text=%7B%7Btext%7D%7D&model_id=5&speaker_name=tsukuyomi-chan&sdp_ratio=0.5&noise=0.6&noisew=0.8&length=1.1&language=JP&auto_split=True&split_interval=0.5&assist_text=&assist_text_weight=0.6&style=Neutral&style_weight=5

```
ちなみに、話者名(speaker_name)は、モデルに基本的に一つしかないです

**Comment by shikichrome** [comment]
そうですね.../models/infoにはこう書かれています、
{"0":{"config_path":"model_assets\\9S\\config.json","model_path":"model_assets\\9S\\9S.safetensors","device":"cpu","spk2id":{"9S":0},"id2spk":{"0":"9S"},"style2id":{"Neutral":0,"怒り":1,"悲しみ":2,"喜び":3,"普通":4}},"1":{"config_path":"model_assets\\leona\\config.json","model_path":"model_assets\\leona\\leona_e100_s1100.safetensors","device":"cpu","spk2id":{"leona":1},"id2spk":{"1":"leona"},"style2id":{"Neutral":0,"怒り":1,"悲しみ":2,"喜び":3,"普通":4}},"2":{"config_path":"model_assets\\leonasan\\config.json","model_path":"model_assets\\leonasan\\leonasan_e100_s1900.safetensors","device":"cpu","spk2id":{"leonasan":0},"id2spk":{"0":"leonasan"},"style2id":{"Neutral":0}}}
この場合model_idとspeaker_nameは2とleonasanとかですか....？

**Comment by OzoneAsai** [comment]
```json

{"0":{"config_path":"model_assets\9S\config.json","model_path":"model_assets\9S\9S.safetensors","device":"cpu","spk2id":{"9S":0},"id2spk":{"0":"9S"},"style2id":{"Neutral":0,"怒り":1,"悲しみ":2,"喜び":3,"普通":4}},"1":{"config_path":"model_assets\leona\config.json","model_path":"model_assets\leona\leona_e100_s1100.safetensors","device":"cpu","spk2id":{"leona":1},"id2spk":{"1":"leona"},"style2id":{"Neutral":0,"怒り":1,"悲しみ":2,"喜び":3,"普通":4}},"2":{"config_path":"model_assets\leonasan\config.json","model_path":"model_assets\leonasan\leonasan_e100_s1900.safetensors","device":"cpu","spk2id":{"leonasan":0},"id2spk":{"0":"leonasan"},"style2id":{"Neutral":0}}}
この場合model_idとspeaker_nameは2と

```
読みにくいのでハイライト入れますね

**Comment by OzoneAsai** [comment]
1でleonaまたは2でleonaさんであってるとおもいますよ

**Comment by shikichrome** [comment]
なるほどです、ありがとうございます
