### ISSUE TITLE
Google Colabで動かすことはできますか？

### ISSUE THREAD

**Issue by t-g-tg** [litagin02/Style-Bert-VITS2#59]
すごく便利なツールをありがとうございます！macを使っていて、parallelsの仮想windows環境で動かしてみたんですが、音声の精度の高さに驚いています。スペックの関係もあってgoogle colabとかで動かせると便利だなと思ったんですが、非エンジニアのど素人なものでなかなかうまくできず…　もしcolabでも動かせそうだったらやり方教えていただけると大変ありがたいです！

**Comment by litagin02** [comment]
http://colab.research.google.com/github/litagin02/Style-Bert-VITS2/blob/master/colab.ipynb
音声合成をやりたいか学習をやりたいかにもよりますが、READMEにあるこれはそのまま使えると思います
デフォルトモデルの場合を使いたい場合は、最初の方の
```
!python initialize.py --skip_jvnv
```
を
```
!python initialize.py
```
へ変える必要があります。

またMacOSでもおそらく手動でPython環境を構築すれば動くとは思います。

**Comment by litagin02** [comment]
> ありがとうございます。
> 学習は問題なく行えました。デフォルトモデルを使った音声合成もcolabでできたらと思っています。

colabでもデフォルトモデルの音声合成はできます（上で書いた通り`--skip_jvnv`を削ってやれば）

**Comment by t-g-tg** [comment]
学習用のcolabで/content/MyDrive/Style-Bert-VITS2/model_assets/にデフォルトモデルを置けば動いたのでそれで使おうと思います。ありがとうございました！
