### ISSUE TITLE
日本語変換の読み修正・辞書の使用・ユーザー辞書実装

### ISSUE THREAD

**Issue by litagin02** [litagin02/Style-Bert-VITS2#60]
現在の日本語の読み変換はpyopenjtalk（OpenJTalk）のものをそのまま使っていますが、誤りがたびたび起こりエラーになることがよく報告されています。

問題点：
- 学習時：自動書き起こしを使った場合特に、不自然な日本語や変な漢字の使用や微妙な書き起こしが生成されることがあり、テキストの前処理段階でそれはエラーになる
- 生成時：読んで欲しい読み方とは違う読み方をされたり、読みが分からずエラーになる

あったらいいもの：
1. 生成時に、現在のアクセント修正のように読みも修正・指定できるようにしたい
2. そもそもpyopenjtalkの最新GitHub版ではユーザー辞書機能が実装されているので、公開されている大きい辞書や、またユーザーが単語登録csv等を作ることにより、pyopenjtalkに読みを与えることができる

困難・めんどくささ：
1. について。コード上原理的には読み修正は簡単にできるが、WebUI上でいい感じにやるデザインが分からない（そもそも現在のアクセント調整UIもかなりアレ）
2. について。現在は依存関係としてpyopenjtalk-prebuiltを使っており、これはpyopenjtalk 0.3.0のビルドであり、ユーザー辞書機能はない。ビルドをどうにかするにしてもpypiにあるpyopenjtalkでもまだユーザー辞書機能はないので、自分でビルドしてそれを使ってもらうようにするのがいいか（wheelやらC++ビルドやら自分が全く知らないけど頑張ればできるかもしれない）。

現在はとりあえずpyopenjtalkのユーザー辞書機能を追加実装する方向で少しいろいろ試してみています。

**Comment by litagin02** [comment]
https://zenn.dev/syoyo/articles/4f6962247adfb6
これを参考にしてpyopenjtalkのビルドを作ってそこからpipで取ってくるようにすることを考えています

そうですね、VOICEVOXはVue等を使っているようです。現在はシンプルなGradioのWebUIなのでUIをうまくつくるのは難しそうです。

**Comment by litagin02** [comment]
https://pypi.org/project/pyopenjtalk-dict/
pyopenjtalkの現在のgithub最新版（辞書機能付き）のwheelをpypiにデプロイしました。
とりあえず辞書機能は使えるようになったようです。
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/139731664/0d36173a-c537-491b-b153-c463bc8f9f76)

**Comment by OzoneAsai** [comment]
リリースは文字起こしモデルの新規対応が完了したらですかね？

**Comment by litagin02** [comment]
まだcsvファイル（指定された書式）での辞書が読み込めるようになったというだけなので、具体的によさそうな辞書を追加したりユーザーが単語登録できる仕組み（最低限csvとかを書いてもらったり）の枠組みを作ってからだと思います。

**Comment by WariHima** [comment]
style-bert-vits2の読み方がわからなくてエラーが起きる問題につてですが
たぶんpyopenjtalkの形態素解析の後にひらがなやアルファベット以外の文字が残った場合の例外処置がない事が原因だと推測しています。
エラーが起きた時にエラー位置の読み方を登録させてユーザー辞書を作成できるようにするといい気がします。

方法①入力された文章をpyopenjtalkの処理を通す前に辞書(ユーザー辞書含む)に含まれていない文字を専用コードに変換。(専用コードは辞書にエラーとか読み方を登録しておく)。
一応エラーが起きても読み上げられるようになる。
方法②openjtalk側を直したうえでエラー位置を返すようにする。

**Comment by OzoneAsai** [comment]
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\preprocess_text.py", line 146, in <module>
    preprocess()
  File "C:\WorkSpace\Style-Bert-VITS2\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\WorkSpace\Style-Bert-VITS2\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\WorkSpace\Style-Bert-VITS2\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\WorkSpace\Style-Bert-VITS2\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\WorkSpace\Style-Bert-VITS2\preprocess_text.py", line 58, in preprocess
    norm_text, phones, tones, word2ph = clean_text(
  File "C:\WorkSpace\Style-Bert-VITS2\text\cleaner.py", line 11, in clean_text
    phones, tones, word2ph = language_module.g2p(norm_text, use_jp_extra)
  File "C:\WorkSpace\Style-Bert-VITS2\text\japanese.py", line 185, in g2p
    sep_text, sep_kata = text2sep_kata(norm_text)
  File "C:\WorkSpace\Style-Bert-VITS2\text\japanese.py", line 364, in text2sep_kata
    raise ValueError(f"Cannot read: {word} in:\n{norm_text}")
ValueError: Cannot read: 々 in:
今度はまた急に......何々主義だの,何々主義だの......

**Comment by litagin02** [comment]
前処理時の挙動で、現在は読めないところで一つ一つエラーが出ていますが、これは不評なので、一度全て処理し（読めないデータは飛ばす）、エラーがおきた箇所を後で確認して必要なら修正する、という形にする予定です：
https://github.com/litagin02/Style-Bert-VITS2/commit/4c8ea82959890b30aa1c01cab065b949436f57ed

**Comment by litagin02** [comment]
ver 2.3にてユーザー辞書機能を実装したためここはクローズします
