### ISSUE TITLE
書き起こし：Whisper Large-v3 only can use 4GB VRAM

### ISSUE THREAD

**Issue by add63sugar** [litagin02/Style-Bert-VITS2#65]
Hi.
My graphic card is 4070tis with 16GB VRAM. When I am doing「書き起こし」by Whisper Large-v3, it only allow using 4GB VRAM.
If the data set is large, (around 2000 files), it sometime will become very slow.
Is this normal or a bug?

**Comment by litagin02** [comment]
I don't change any behavior of whisper from faster-whisper, so I think it's normal.
You can choose computation type such as int8 or int16 instead of bfloat16 to speedup, or maybe smaller model than large-v2.
