### ISSUE TITLE
アクセント調整機能について

### ISSUE THREAD

**Issue by Aspena2022** [litagin02/Style-Bert-VITS2#66]
![style_error01](https://github.com/litagin02/Style-Bert-VITS2/assets/109154669/19250c7a-5b07-4171-ba88-c8d569b7e401)

アクセント調整のチェックボックスをオンにしたままテキストを変更し、合成すると
**アクセント指定が不正です**のエラーになります。
テキストとアクセントの齟齬のせいですが、アクセント文字列を再取得すべきなのと、
テキスト変更時には自動的にチェックボックスをオフにすべきでしょう。

そして、エラーが起きたときにボリューム設定がいちいちMAX値に戻ります。
フルボリュームをデフォルト値にしているようですが、環境によってはフルボリュームは耳をつんざく轟音になりますよ。設定したボリューム値を維持してください。

**Comment by litagin02** [comment]
ご意見ありがとうございます。
> テキストとアクセントの齟齬のせいですが、アクセント文字列を再取得すべきなのと、
テキスト変更時には自動的にチェックボックスをオフにすべきでしょう。

アクセント文字列の再取得はどのタイミングで行うのがよいと思われるでしょうか？またテキスト変更時のチェックボックスオフとはどこのチェックボックスについてでしょうか。

> そして、エラーが起きたときにボリューム設定がいちいちMAX値に戻ります。

これについては、内部では何も音量ボリューム調整等の設定はしていません。おそらく環境由来やGradioの音声ファイル処理やブラウザの再生処理に依存していそうなので、原因が分からず、解決できるかは分かりません。

**Comment by Aspena2022** [comment]
昨日**app.py**を読んでいたのですがボリュームに関してはGradio側の処理らしいですね。

アクセント指定エラーを回避するためにいろいろ試していたのですが、
こんな方法を思いつきました。

１）入力テキストが変更されたらトーンをクリアする
２）音声合成完了後に、アクセント調整のチェックボックスをオフに戻す

これでテキストとアクセントの齟齬が一応なくなります。

１の部分のコード：
```
                use_tone = gr.Checkbox(label="アクセント調整を使う", value=False)
                use_tone.change(
                    lambda x: (gr.Checkbox(value=False) if x else gr.Checkbox()),
                    inputs=[use_tone],
                    outputs=[line_split],
                )

                #20240216 ----------------------------------------------------------
                #トーンが設定済のときに、テキストが更新されたら、トーンを消す
                if tone is not None:
                    text_input.change(
                       lambda x: (tone:=None),
                       inputs=[text_input],
                       outputs=[tone],
                    )
                #--------------------------------------------------------------------

```

２の部分のコード：
```
                tts_button = gr.Button(
                    "音声合成（モデルをロードしてください）",
                    variant="primary",
                    interactive=False,
                )
                text_output = gr.Textbox(label="情報")

                #20240216 -----------------------------------------------------------
                #合成完了後にtext_outputが更新されるので、そのタイミングでアクセント調整のuse_toneのチェックボックス
                #をオフにする　テキストとアクセントがズレるとエラーが起きる現象を回避するため
                text_output.change(
                    lambda x: (gr.Checkbox(value=False)),
                    inputs=[text_output],
                    outputs=[use_tone],
                )
                #--------------------------------------------------------------------

```


これでどこを修正したかわかると思いますが、**app.py**も一応添付しておきます。
拡張子を .txt に変更しておきました。　
[app.txt](https://github.com/litagin02/Style-Bert-VITS2/files/14316463/app.txt)

１の if tone is not None: の判定はうまくいってないみたいですが、まぁ動いています。

**Comment by litagin02** [comment]
ありがとうございます、取り入れてその方向で調整をしたいと思います。

**Comment by litagin02** [comment]
アクセントはエディターのほうが使いやすいと思うのでこちらはクローズします
