### ISSUE TITLE
ユーザー辞書で扱えない単語がある

### ISSUE THREAD

**Issue by Aspena2022** [litagin02/Style-Bert-VITS2#74]
2.3のユーザー辞書ですが、例えばローファーなど、「**ー**」で終わる単語が反映されません。
OpenJTalkのg2p周りぽいですが。

**Comment by litagin02** [comment]
「ローファー」の読みを「ロオファア」、アクセントを「低高高高高」で試してみたところ、優先度が標準では「ローファーを履く」のアクセントが反映されませんでしたが、優先度を高にすると反映されました。これで解決になっていますでしょうか？
アクセント等が反映されない場合は優先度を上げてもらって試してもらうとよいと思います。

**Comment by Aspena2022** [comment]
たしかに、優先度を高くすれば反映されました。
標準だとダメっていうのはちょっと曲者ですね。

**Comment by litagin02** [comment]
優先度の実際の数値設定はVOICEVOXのものをそのまま使っており、そちらでは「反映されない場合は優先度を上げて」という説明があるようです。

この説明を追加することは考えておきます。
辞書自体は機能するようなのでクローズさせていただきます。

**Comment by luvwinnie** [comment]
素晴らしいオープンソース，ありがとうございます！
今ユーザー辞書で，以下の部分を追加してみたのですが，記号のような部分がもしかしたらMecabで扱えない。。？

なにか良い手立てはないでしょうか。

```
C,,,8609,名詞,固有名詞,一般,*,*,*,C,シー,シー,0/3,*
C++,,,8609,名詞,固有名詞,一般,*,*,*,C++,シープラスプラス,シープラスプラス,0/3,*
C#,,,8609,名詞,固有名詞,一般,*,*,*,C#,シープシャープ,シープシャープ,0/3,*
```
