### ISSUE TITLE
ペースト時に改行で分割を！

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#77]
Editorでは、テキストをペーストしたとき、テキストエリアではないがために改行の情報を捨ててしまっているが、これでは長すぎる。
自動でペーストされる内容の改行を認識して分割する機能は難しいような気がしたので、句点で分割する機能(Optional)をお願いします。

**Comment by litagin02** [comment]
https://github.com/litagin02/Style-Bert-VITS2-Editor
こちらのほうでお願いします。
（改行は文字コードで取得できるので、技術的には改行で分けることは可能であると思います、考えておきます。）
