### ISSUE TITLE
story style

### ISSUE THREAD

**Issue by yiwei0730** [litagin02/Style-Bert-VITS2#84]
I would like to ask your opinion on the changes in the narrative.
When a storyteller is telling a story, the way he or she speaks should be different when the narration is speaking and when the characters are speaking. For example: At this time, my mother said: "Children, you should study hard."
The area marked "Children, you should study hard" should be more vivid, while the narration part will be relatively dull. How to implement this setting will be better.

**Comment by OzoneAsai** [comment]
Prepare some nice dataset can realize it I think.
In JP_Extra, I prepared 16 hours dataset and it worked so nice. But actually I don't think it requires such a long dataset.

**Comment by yiwei0730** [comment]
Just need raw audio (like LibriTTS) or a more emotional collection style, or more like a storyteller?
How about the style generator? 

""model = Model.from_pretrained("pyannote/wespeaker-voxceleb-resnet34-LM")""

I have seen some different wav style generators. There is a new w2v2.0-bert released in 2023/12. Will it have better audio performance than the current style?

**Comment by litagin02** [comment]
In inference (app.py or server_editor.py), you can choose styles and weights from the style vectors you made and you can control it.
